version: '3.3'
services:
  db:
    image: postgres:14
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 5436:5432
    networks:
      - somenet
  bot:
    image: python-bot
    build: .
    command: sh -c "python3 -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    ports:
      - 5500:5000
    networks:
      - somenet

networks:
  somenet:
    driver: bridge
