dict_types = {
    'Phila': 'Філадельфія',
    'Californ': 'Каліфорнія',
    'Futumack': 'Футомакі',
    'WarmRols': 'Гарячі роли',
    'Dragon': 'Дракон',
    'Maki': 'Макі',
    'Set': 'Сети',
    'pig': 'Страви з свинини',
    'bif': 'Страви з яловичини',
    'chiken': 'Страви з курки',
    'fish': 'Страви з риби',
    'sideDishes': 'Гарніри',
    'pasta': 'Паста',
    'mangal': 'Страви на мангалі',
    'alcoholic': 'Алкогольні',
    'nonAlcoholic': 'Безалкогольні',
    'shot': 'Шоти',
    'horilka': 'Горілка',
    'wine': 'Вино',
    'beer': 'Пиво',
    'cognac': 'Коньяк',
    'whiskey': 'Віскі',
    'likers': 'Лікери',
    'shamp': 'Шампанське'
}
menu_types = {
    'pizza': 'menu_pizza',
    'salats': 'menu_salats',
    'firstDish': 'menu_first_dish',
    'secondDish': 'menu_second_dish',
    'coldSnacks': 'cold_snacks',
    'warmSnacks': 'warm_snacks',
    'drinks': 'menu_drinks',
    'deserts': 'menu_deserts',
    'coctails': 'menu_coctails',
    'alcohol': 'menu_alcohol',
    'sushi': 'menu_sushi'
}
